### PR TITLE
Version 3.600

### PR DESCRIPTION
**Pull request by yanone**
* Took @Fonthausen’s latest sources from https://github.com/Fonthausen/NunitoSans/tree/ComponentTest/10%20Sources
* Added missing glyphs acaron and adotaccent (+ capitals)
* Generated new static fonts
* Updated build script
* Updated metadata
* Bumped version to 3.6 (identical across all current Nunito/NunitoSans/Mulish upgrades)

### CODE REVIEW

**Comment by yanone** [comment]
Bumped version to 3.601
* Static fonts are now properly hinted (was opposite)
* VFs are note unhinted (was opposite)

**Comment by yanone** [comment]
Bumped to version 3.602:
* Corrected `perthousand`

**Comment by davelab6** [comment]
@fonthausen and @m4rc1e how do you want to proceed with this? @yanone is now on vacation, so I propose we merge this trusting he did all the right things, and proceed with https://github.com/google/fonts/pull/2520 too, and if the GF process gets stuck, then figure out if we should revert this PR or what...

**Comment by Fonthausen** [comment]
@davelab6 I am fine with that.

**Pull request merged**
